### PR TITLE
Jenkins pipeline support

### PR DESCRIPTION
**Pull request by fanatic**
Tried to avoid changing the older code too much, but needed to convert AbstractBuild -> Run, AbstractProject -> Job, and BuildListener -> TaskListener.

I couldn't figure out how to change the jenkins version to something lower without a compatibility issue with the pipeline plugin when I was testing.  It probably also needs a major version bump although non-pipeline jobs still work.

### CODE REVIEW

**Comment by ericsysmin** [comment]
Any updates on this? Curious cause I could really use this.

**Comment by bkaganyildiz** [comment]
Thank you so much for your contribution, I've just get notified about the pr. After a review and testing I'll merge and deploy plugin.

**Comment by ericsysmin** [comment]
@fanatic do you have an example of how to call this in the pipeline?

**Comment by fanatic** [comment]
Super simple :) . OpsGenie is configured with an api key and team in my "Manage Jenkins" settings, then I can just call it.  I imagine you can override tags, teams, apiKey, and apiUrl via arguments, but I haven't tried it. 

```
  post {
    always {
      opsgenie()
    }
  }
```

**Comment by ericsysmin** [comment]
@fanatic I noticed that when using with pipeline you get stuff like `[Jenkins] Project : master with status: FAILURE` as the incident subject, how do we get it to return the actual job name?

**Comment by fanatic** [comment]
Good question.  Our OpsGenie is connected to Slack, and I see a bunch of details, including context we add.

image

I think you get to configure the incident subject in the OpsGenie UI:

image

**Pull request merged**
